### PR TITLE
Explicitly Convert Wheel Delta

### PR DESCRIPTION
**Pull request by bobonthenet**
Looks like my editor automatically removed a bunch of white space too. The only real change is wrapping delta * WHEEL_DELTA in the int() function. The wheel method gives the error "ctypes.ArgumentError: argument 4: <class 'TypeError'>: Don't know how to convert parameter 4" without it.

### CODE REVIEW

**Comment by boppreh** [comment]
Good catch. There should be some way to scroll fractional units (for an example see touchpads), but for now it's better to just not throw an error.

Thanks a lot for the contribution. The whitespace changes are also helpful.

**Comment by boppreh** [comment]
I always forget you have to merge before commenting and closing... Sorry about that.

**Comment by bobonthenet** [comment]
How soon will this change be included in the pip package? I know absolutely nothing about managing packages.

**Comment by boppreh** [comment]
Pip updates are triggered by the developer. If you are curious about the process:

- Bumping the version in `setup.py` and running `python setup.py sdist upload` is sufficient to package and upload to PyPI. However for this project we also need to...
- Run tests to make sure nothing is too broken or missing too much coverage.
- Decide the new version based on [Semantic Versioning](http://semver.org/).
- Update `CHANGES.md` listing what has changed.
- Update API docs in `README.md`.
- Convert docs into RST text format for PyPI.
- Add a Git tag with the new version number.
- Push changes to GitHub.
- Create a new Github release listing the changes and including the source code compressed files.

Thankfully this was all automated a while ago in `make_release.py`.

**Comment by boppreh** [comment]
I've uploaded a new version to PyPI. but apparently three steps of the automated workflow are now broken (and only one of them is my fault).

But you can already do `pip install --upgrade keyboard` to install the newest version with your changes.

**Comment by bobonthenet** [comment]
Thank you! I am really liking this library.

**Pull request merged**
