### PR TITLE
Fix for Mac command key

### PR DESCRIPTION
**Pull request by glitchassassin**
Haven't noticed because I didn't upgrade my version of `keyboard`, but "command" is currently broken on Mac. This should fix it.

### CODE REVIEW

**Comment by boppreh** [comment]
That dictionary is a table of canonical names, to ensure that a user listening for <kbd>ctrl</kbd> still matches when the user issues an event with name <kbd>control</kbd>. Event names are translated when the user requests for them (e.g. setting up a hotkey) or when the system generates them. So the proposed change would be equivalent to simply removing the line.

The mapping <kbd>command</kbd> to <kbd>windows</kbd> was added to allow cross-platform hotkeys, so both <kbd>win+t</kbd> and <kbd>command+t</kbd> work (and unbeknownst to the user, the underlying name is <kbd>windows</kbd>).

I think it would be best to keep the mapping and fix the underlying problem.

**Comment by glitchassassin** [comment]
Reverted the previous change and added a mapping in `_darwinkeyboard.py` instead.

I left "command" in the non_layout_keys table, and explicitly mapped "windows" to "command" to avoid confusion.

**Comment by boppreh** [comment]
Sorry for not responding earlier, for some reason I didn't receive any notifications.

Mapping "windows -> command" in the OS-specific part means that a Mac OS user that tries to port their script to Windows/Linux will find "command" doesn't work, but a Windows/Linux user will be able to use their "windows" hotkeys just fine. That's a bit weird.

I understand that reporting a "windows" key press in a Mac is also strange. Maybe we can try to fix this while keeping the "windows <-> command" mapping everywhere else? Not normalizing the name when creating the event should be enough.

Regarding "delete"/"backspace", I think you are qualified to make a decision here.

By the way, since you have been so helpful and is depending on this library for you `lackey` project, I'm going to add you as a contributor, specially to give you more power regarding the Mac OS parts.

**Comment by glitchassassin** [comment]
That's a good point; it should work in both directions. Let me think if there's a better way to implement this.

**Comment by glitchassassin** [comment]
Why not just make the canonical names different for each platform, but reversible?

For example, the canonical name on Mac for "command", "windows", "cmd", or "win" would be "command". On Windows, the canonical name for all of the above would be "windows".

This would correctly report a "windows" key press on Windows, and a "command" key press on Mac, but cross-platform code would work fine: whether you specified a hotkey with "cmd" or "win" it would trigger appropriately on either platform.

I've updated my pull request with an example of what I'm talking about.

**Comment by glitchassassin** [comment]
There are only a couple keys where this is affected (command/windows, backspace/delete). What about the Linux "meta" key name?

**Comment by boppreh** [comment]
I was trying to finish the suppress branch rewrite before merging this, but it's taking too long. I'm sorry I made you wait this much already.

Great contribution as always, thank you.

**Pull request merged**
